name: heurististics

services:
  client:
    image: azamserver/heurististics:client-latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - UI_PORT=3000
  server:
    image: azamserver/heurististics:server-latest
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - API_PORT=3000
      - API_LOG_LEVEL=info
      - API_CORS_ORIGIN=*
